#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
import numpy as np

#create array using numpy

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [2]:

## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [3]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [4]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
# Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
## Attributes
arr=np.array([[1,2,3,4,5],[4,5,6,7,8]])

print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

[[1 2 3 4 5]
 [4 5 6 7 8]]
(2, 5)
2
10
int64
8


In [8]:
# Numpy vectorized operations

arr1=np.array([1,2,3,4,5])

arr2=np.array([6,7,8,9,10])

print(arr1+arr2)

print(arr2-arr1)

print(arr1*arr2)

print(arr2/arr1)

[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]
[6.         3.5        2.66666667 2.25       2.        ]


In [9]:
# Universal Functions

arr=np.array([1,2,3,4,5])

print(np.sqrt(arr))

print(np.exp(arr))

print(np.sin(arr))

print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [10]:
# Array Slicing and Indexing

arr=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

print(arr)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [11]:
arr[1:,1:3]

array([[3, 4],
       [4, 5]])

In [13]:
print(arr[0][0])

1


In [14]:
arr[0:2,2:]

array([[3, 4],
       [4, 5]])

In [15]:
arr[1:,2:]

array([[4, 5],
       [5, 6]])

In [16]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1

data=np.array([1,2,3,4,5])

#mean and SD
mean=np.mean(data)
std_div=np.std(data)

# Normalize
norm_data=(data-mean)/std_div
print(norm_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [17]:
## Logical Operations

data=np.array([1,2,3,4,5,6,7,8,9])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])