### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## Creating Numpy Arrays

In [1]:
import numpy as np

a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
#2D AND 3D

b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
#d type
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [6]:
#np.arange

np.arange(1, 11,2)

array([1, 3, 5, 7, 9])

In [7]:
#with reshape

np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [8]:
# ones and zeroes used for array inistialisation

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# np.random

np.random.random((3,4))

array([[0.08387829, 0.6784844 , 0.55702221, 0.10034362],
       [0.0552029 , 0.60531137, 0.35940191, 0.97341229],
       [0.68732224, 0.72245188, 0.31370189, 0.30639123]])

In [12]:
# linspace

np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [14]:
# identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [16]:
a1=np.arange(10, dtype=int)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [17]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [19]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [20]:
# ndim

a3.ndim

3

In [21]:
#shape

print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
# size

print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [23]:
# item size

a3.itemsize

8

In [24]:
#dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


#### Changing Datatype

In [25]:
# astype

a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Array Operations

In [27]:
a1=np.arange(12).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
# scalar operations

a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [29]:
a1==9

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False]])

In [31]:
a2=np.arange(12, 24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
# vector operations

a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

## Array Functions

In [34]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[24., 67., 11.],
       [70., 18., 45.],
       [50., 38., 37.]])

In [39]:
# max/min/sum/prod
# axis=1-> row 0-> col
np.max(a1, axis=1)
np.min(a1, axis=0)
np.sum(a1, axis=1)
np.prod(a1,axis=0)

array([84000., 45828., 18315.])

In [44]:
#mean/median/std/var

np.mean(a1)
np.median(a1)
np.std(a1,axis=0)
np.var(a1, axis=1)

array([572.66666667, 450.88888889,  34.88888889])

In [48]:
# dot product
a1
a2=np.arange(9).reshape(3,3)
np.dot(a1,a2)

array([[267., 369., 471.],
       [324., 457., 590.],
       [336., 461., 586.]])

In [50]:
# log and exponents

np.log(a1)
np.exp(a1)

array([[2.64891221e+10, 1.25236317e+29, 5.98741417e+04],
       [2.51543867e+30, 6.56599691e+07, 3.49342711e+19],
       [5.18470553e+21, 3.18559318e+16, 1.17191424e+16]])

In [55]:
#round/floor/ceil

np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)

array([[41., 71., 51.],
       [85., 52., 89.]])

## Indexing and Slicing

In [56]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a2=np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [62]:
#Indexing

a2[1,0]
a3[1,0,1]

5

In [67]:
# slicing

a1
a1[2:5:2]
a2
a2[0:2,1::2]
a3
a3[::2,0,::2]

array([[0]])

## Iterating

In [68]:
a1

for i in a1:
  print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 

In [69]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7


## Reshaping

In [70]:
#Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [71]:
#ravel
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

## Stacking

In [76]:
#horizaontal stacking

a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

np.hstack((a4,a5))

#Vertical Stacking

np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

In [77]:
#horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [80]:
#Vertical spliting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [84]:
np.vsplit(a5,1)

[array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]